service: budget-tracker
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.updateSheet
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true
